const recentTransactionsCache = [
  {
    id: "tx1001",
    account: "Tangerine Chequing",
    amount: 500.00,
    direction: "withdrawal",
    date: "2025-07-30",
    memo: "Transfer Out to Wealthsimple TFSA",
    isMatchedTransfer: false,
  },
  {
    id: "tx1002",
    account: "Wealthsimple TFSA",
    amount: 500.00,
    direction: "deposit",
    date: "2025-07-31",
    memo: "Transfer In from Tangerine Chequing",
    isMatchedTransfer: false,
  },
  {
    id: "tx1003",
    account: "Tangerine Savings",
    amount: 1200.00,
    direction: "withdrawal",
    date: "2025-07-25",
    memo: "Bill Payment",
    isMatchedTransfer: false,
  },
  {
    id: "tx1004",
    account: "Tangerine Chequing",
    amount: 1200.00,
    direction: "deposit",
    date: "2025-07-25",
    memo: "Deposit paycheck",
    isMatchedTransfer: false,
  },
  {
    id: "tx1005",
    account: "Wealthsimple TFSA",
    amount: 200.00,
    direction: "withdrawal",
    date: "2025-07-29",
    memo: "Transfer Out to Tangerine Chequing",
    isMatchedTransfer: false,
  },
  {
    id: "tx1006",
    account: "Tangerine Chequing",
    amount: 200.00,
    direction: "deposit",
    date: "2025-07-30",
    memo: "Transfer In from Wealthsimple TFSA",
    isMatchedTransfer: false,
  },
];
